version: "2"
services:
  client:
    image: webapp-client
    restart: always
    ports:
      - "3000:3000"
    working_dir: /client/src
    volumes:
      - ./client:/client/src
    links:
      - backend
    networks:
      - webappnetwork

  backend:
    image: webapp-backend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb
    networks:    
      - webappnetwork

  mongodb:        
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - webappnetwork

networks:    
  webappnetwork:        
    driver: bridge